## **What is Pandas?**
Pandas is a powerful and flexible open-source data analysis and manipulation library for Python.

Python library used for working with structured data sets (tables). It has functions for analyzing, cleaning, exploring, and manipulating data. Similar to data tables in SQL and Excel.

#### **Install pandas**

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
# import pandas
import pandas as pd

In [3]:
pd.__version__ # check installed pandas version

'2.3.3'

### **What is Dataframe?**
It's a structured data constructed with rows and columns, similar to a SQL tables or Excel tables

#### **1. Create Dataframe**

In [4]:
# using a List
df = pd.DataFrame([10, 22, 35], columns=['Col_Name'])
print(df)

   Col_Name
0        10
1        22
2        35

In [5]:
print(type(df)) # check data type

<class 'pandas.core.frame.DataFrame'>

In [6]:
# using Dictionary of Lists
data = {
    'Name': ['Tanmoy', 'Usha', 'Achol', 'Samiya', 'Nizum', 'Talha', 'Rodoshi', 'Rafi', 'Ayan', 'Ahmed'],
    'Age': [30, 18, 25, 20, 22, 15, 18, 12, 10, 8],
    'Salary': [30000, 20000, 15000, 10000, 8000, 12000, 22000, 45000, 5000, 7000]
}

In [7]:
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0   Tanmoy   30   30000
1     Usha   18   20000
2    Achol   25   15000
3   Samiya   20   10000
4    Nizum   22    8000
5    Talha   15   12000
6  Rodoshi   18   22000
7     Rafi   12   45000
8     Ayan   10    5000
9    Ahmed    8    7000

In [9]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

#### **2. Basic Dataframe Understanding**

In [16]:
df.head(5) # top rows

     Name  Age  Salary
0  Tanmoy   30   30000
1    Usha   18   20000
2   Achol   25   15000
3  Samiya   20   10000
4   Nizum   22    8000

In [17]:
df.tail(5) # last rows

      Name  Age  Salary
5    Talha   15   12000
6  Rodoshi   18   22000
7     Rafi   12   45000
8     Ayan   10    5000
9    Ahmed    8    7000

In [18]:
df.shape # returns a tuple containing the shape of the DataFrame - rows & columns

(10, 3)

In [19]:
df.columns # list of column names in a dataframe

Index(['Name', 'Age', 'Salary'], dtype='object')

In [20]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True) # rename column name/s

In [21]:
df

      Name  Age  Monthly_Salary
0   Tanmoy   30           30000
1     Usha   18           20000
2    Achol   25           15000
3   Samiya   20           10000
4    Nizum   22            8000
5    Talha   15           12000
6  Rodoshi   18           22000
7     Rafi   12           45000
8     Ayan   10            5000
9    Ahmed    8            7000

In [22]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            10 non-null     object
 1   Age             10 non-null     int64
 2   Monthly_Salary  10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [23]:
df.describe() # describe method generates descriptive statistics of DataFrame, only for numerical-value columns

           Age  Monthly_Salary
count  10.0000       10.000000
mean   17.8000    17400.000000
std     6.8443    12420.413305
min     8.0000     5000.000000
25%    12.7500     8500.000000
50%    18.0000    13500.000000
75%    21.5000    21500.000000
max    30.0000    45000.000000

#### **3. Save and Load data from csv**

In [24]:
df.to_csv('Test_data.csv', index=False) # save file - export data frame

In [25]:
load_df= pd.read_csv('Test_data.csv') # load file - import dataframe
load_df

      Name  Age  Monthly_Salary
0   Tanmoy   30           30000
1     Usha   18           20000
2    Achol   25           15000
3   Samiya   20           10000
4    Nizum   22            8000
5    Talha   15           12000
6  Rodoshi   18           22000
7     Rafi   12           45000
8     Ayan   10            5000
9    Ahmed    8            7000

#### **4. Rows & Columns - Selection**

In [26]:
# select single column
df[['Name']]

      Name
0   Tanmoy
1     Usha
2    Achol
3   Samiya
4    Nizum
5    Talha
6  Rodoshi
7     Rafi
8     Ayan
9    Ahmed

In [27]:
# select multiple columns
df[['Name', 'Monthly_Salary']]

      Name  Monthly_Salary
0   Tanmoy           30000
1     Usha           20000
2    Achol           15000
3   Samiya           10000
4    Nizum            8000
5    Talha           12000
6  Rodoshi           22000
7     Rafi           45000
8     Ayan            5000
9    Ahmed            7000

In [28]:
# select single row || loc - label based index
df.loc[df.Name=='Usha']

   Name  Age  Monthly_Salary
1  Usha   18           20000

In [34]:
# select multiple rows || loc - label based index
df.loc[(df.Name=='Tanmoy') & (df.Monthly_Salary>=20000)]

     Name  Age  Monthly_Salary
0  Tanmoy   30           30000

In [35]:
df.loc[0:2] # [start:stop:step]

     Name  Age  Monthly_Salary
0  Tanmoy   30           30000
1    Usha   18           20000
2   Achol   25           15000

In [36]:
# Select Rows || iloc - index-value based
df.iloc[0]

Name              Tanmoy
Age                   30
Monthly_Salary     30000
Name: 0, dtype: object

In [37]:
df.iloc[0:2] # [start:stop:step]

     Name  Age  Monthly_Salary
0  Tanmoy   30           30000
1    Usha   18           20000

#### **5. Filter Dataframe - Filtering by column values**

In [38]:
df

      Name  Age  Monthly_Salary
0   Tanmoy   30           30000
1     Usha   18           20000
2    Achol   25           15000
3   Samiya   20           10000
4    Nizum   22            8000
5    Talha   15           12000
6  Rodoshi   18           22000
7     Rafi   12           45000
8     Ayan   10            5000
9    Ahmed    8            7000

In [39]:
df_age_filter = df[df['Age'] >= 18] # filter and store dataframe in a new variable

In [40]:
df_age_filter

      Name  Age  Monthly_Salary
0   Tanmoy   30           30000
1     Usha   18           20000
2    Achol   25           15000
3   Samiya   20           10000
4    Nizum   22            8000
6  Rodoshi   18           22000

In [42]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 15000)] # multiple filter conditions

      Name  Age  Monthly_Salary
0   Tanmoy   30           30000
1     Usha   18           20000
2    Achol   25           15000
6  Rodoshi   18           22000

In [43]:
df.where(df['Age'] >= 18) # where function replace values in a DataFrame based on a condition

      Name   Age  Monthly_Salary
0   Tanmoy  30.0         30000.0
1     Usha  18.0         20000.0
2    Achol  25.0         15000.0
3   Samiya  20.0         10000.0
4    Nizum  22.0          8000.0
5      NaN   NaN             NaN
6  Rodoshi  18.0         22000.0
7      NaN   NaN             NaN
8      NaN   NaN             NaN
9      NaN   NaN             NaN

In [44]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

           Name           Age Monthly_Salary
0        Tanmoy            30          30000
1          Usha            18          20000
2         Achol            25          15000
3        Samiya            20          10000
4         Nizum            22           8000
5  Not Eligible  Not Eligible   Not Eligible
6       Rodoshi            18          22000
7  Not Eligible  Not Eligible   Not Eligible
8  Not Eligible  Not Eligible   Not Eligible
9  Not Eligible  Not Eligible   Not Eligible

#### **6. Rows and Columns - Operation (Add, update, delete)**

In [45]:
df

      Name  Age  Monthly_Salary
0   Tanmoy   30           30000
1     Usha   18           20000
2    Achol   25           15000
3   Samiya   20           10000
4    Nizum   22            8000
5    Talha   15           12000
6  Rodoshi   18           22000
7     Rafi   12           45000
8     Ayan   10            5000
9    Ahmed    8            7000

In [47]:
# Create a new column
df['Team'] = ['CEO', 'HR', 'CTO', 'DA', 'DS', 'ML', 'DL', 'SWE', 'IT', 'SS']
df

      Name  Age  Monthly_Salary Team
0   Tanmoy   30           30000  CEO
1     Usha   18           20000   HR
2    Achol   25           15000  CTO
3   Samiya   20           10000   DA
4    Nizum   22            8000   DS
5    Talha   15           12000   ML
6  Rodoshi   18           22000   DL
7     Rafi   12           45000  SWE
8     Ayan   10            5000   IT
9    Ahmed    8            7000   SS

In [48]:
# Add new columns using existing column/s
df['Bonus'] = df['Monthly_Salary'] * 0.20
df

      Name  Age  Monthly_Salary Team   Bonus
0   Tanmoy   30           30000  CEO  6000.0
1     Usha   18           20000   HR  4000.0
2    Achol   25           15000  CTO  3000.0
3   Samiya   20           10000   DA  2000.0
4    Nizum   22            8000   DS  1600.0
5    Talha   15           12000   ML  2400.0
6  Rodoshi   18           22000   DL  4400.0
7     Rafi   12           45000  SWE  9000.0
8     Ayan   10            5000   IT  1000.0
9    Ahmed    8            7000   SS  1400.0

In [49]:
# Add new row - at the end of dataframe
df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 2000]
df

       Name  Age  Monthly_Salary Team   Bonus
0    Tanmoy   30           30000  CEO  6000.0
1      Usha   18           20000   HR  4000.0
2     Achol   25           15000  CTO  3000.0
3    Samiya   20           10000   DA  2000.0
4     Nizum   22            8000   DS  1600.0
5     Talha   15           12000   ML  2400.0
6   Rodoshi   18           22000   DL  4400.0
7      Rafi   12           45000  SWE  9000.0
8      Ayan   10            5000   IT  1000.0
9     Ahmed    8            7000   SS  1400.0
10      ABC   21           21000   IT  2000.0

In [50]:
# update value in dataframe using index-name
df.loc[0, 'Monthly_Salary'] = 45000
df

       Name  Age  Monthly_Salary Team   Bonus
0    Tanmoy   30           45000  CEO  6000.0
1      Usha   18           20000   HR  4000.0
2     Achol   25           15000  CTO  3000.0
3    Samiya   20           10000   DA  2000.0
4     Nizum   22            8000   DS  1600.0
5     Talha   15           12000   ML  2400.0
6   Rodoshi   18           22000   DL  4400.0
7      Rafi   12           45000  SWE  9000.0
8      Ayan   10            5000   IT  1000.0
9     Ahmed    8            7000   SS  1400.0
10      ABC   21           21000   IT  2000.0

In [53]:
# update value in dataframe using column-value
df.loc[df.Name=='Tanmoy','Monthly_Salary'] = 30000
df

       Name  Age  Monthly_Salary Team   Bonus
0    Tanmoy   30           30000  CEO  6000.0
1      Usha   18           20000   HR  4000.0
2     Achol   25           15000  CTO  3000.0
3    Samiya   20           10000   DA  2000.0
4     Nizum   22            8000   DS  1600.0
5     Talha   15           12000   ML  2400.0
6   Rodoshi   18           22000   DL  4400.0
7      Rafi   12           45000  SWE  9000.0
8      Ayan   10            5000   IT  1000.0
9     Ahmed    8            7000   SS  1400.0
10      ABC   21           21000   IT  2000.0

In [ ]:
# delete value - rows and columns

In [58]:
# delete row using column-value filter
df = df.drop(df[df.Name == 'ABC'].index) # delete row, axis= 0
df

      Name  Age  Monthly_Salary Team   Bonus
0   Tanmoy   30           30000  CEO  6000.0
1     Usha   18           20000   HR  4000.0
2    Achol   25           15000  CTO  3000.0
3   Samiya   20           10000   DA  2000.0
4    Nizum   22            8000   DS  1600.0
5    Talha   15           12000   ML  2400.0
6  Rodoshi   18           22000   DL  4400.0
7     Rafi   12           45000  SWE  9000.0
8     Ayan   10            5000   IT  1000.0
9    Ahmed    8            7000   SS  1400.0

In [59]:
# delete row using index-name filter
df.drop(9, axis=0)

      Name  Age  Monthly_Salary Team   Bonus
0   Tanmoy   30           30000  CEO  6000.0
1     Usha   18           20000   HR  4000.0
2    Achol   25           15000  CTO  3000.0
3   Samiya   20           10000   DA  2000.0
4    Nizum   22            8000   DS  1600.0
5    Talha   15           12000   ML  2400.0
6  Rodoshi   18           22000   DL  4400.0
7     Rafi   12           45000  SWE  9000.0
8     Ayan   10            5000   IT  1000.0

In [60]:
df.drop('Bonus', axis=1, inplace=True) # delete one column
# df.drop(['Bonus', 'Team'], axis=1, inplace=True) # delete multiple columns

In [61]:
df

      Name  Age  Monthly_Salary Team
0   Tanmoy   30           30000  CEO
1     Usha   18           20000   HR
2    Achol   25           15000  CTO
3   Samiya   20           10000   DA
4    Nizum   22            8000   DS
5    Talha   15           12000   ML
6  Rodoshi   18           22000   DL
7     Rafi   12           45000  SWE
8     Ayan   10            5000   IT
9    Ahmed    8            7000   SS

In [62]:
df.rename(columns={'Monthly_Salary': 'Salary'}, inplace=True) # rename column name
df

      Name  Age  Salary Team
0   Tanmoy   30   30000  CEO
1     Usha   18   20000   HR
2    Achol   25   15000  CTO
3   Samiya   20   10000   DA
4    Nizum   22    8000   DS
5    Talha   15   12000   ML
6  Rodoshi   18   22000   DL
7     Rafi   12   45000  SWE
8     Ayan   10    5000   IT
9    Ahmed    8    7000   SS

In [63]:
# sort values - order values in dataframe by asc or desc order
df.sort_values('Salary') #ascending order, by default

      Name  Age  Salary Team
8     Ayan   10    5000   IT
9    Ahmed    8    7000   SS
4    Nizum   22    8000   DS
3   Samiya   20   10000   DA
5    Talha   15   12000   ML
2    Achol   25   15000  CTO
1     Usha   18   20000   HR
6  Rodoshi   18   22000   DL
0   Tanmoy   30   30000  CEO
7     Rafi   12   45000  SWE

In [64]:
# sort values in descending order
df.sort_values('Salary', ascending=False)

      Name  Age  Salary Team
7     Rafi   12   45000  SWE
0   Tanmoy   30   30000  CEO
6  Rodoshi   18   22000   DL
1     Usha   18   20000   HR
2    Achol   25   15000  CTO
5    Talha   15   12000   ML
3   Samiya   20   10000   DA
4    Nizum   22    8000   DS
9    Ahmed    8    7000   SS
8     Ayan   10    5000   IT

#### **7. working with date value**

In [67]:
# create a date column - date of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03', '2024-04-02', '2024-04-25', '2024-05-10', '2024-05-18', '2024-05-30', '2024-06-22']
df

      Name  Age  Salary Team         DOJ
0   Tanmoy   30   30000  CEO  2024-01-01
1     Usha   18   20000   HR  2024-01-15
2    Achol   25   15000  CTO  2024-03-28
3   Samiya   20   10000   DA  2024-03-03
4    Nizum   22    8000   DS  2024-04-02
5    Talha   15   12000   ML  2024-04-25
6  Rodoshi   18   22000   DL  2024-05-10
7     Rafi   12   45000  SWE  2024-05-18
8     Ayan   10    5000   IT  2024-05-30
9    Ahmed    8    7000   SS  2024-06-22

In [68]:
df['DOJ'].dtype # object-type value

dtype('O')

In [69]:
df['DOJ'] = pd.to_datetime(df['DOJ']) # change to date-time type

In [70]:
df['DOJ'].dtype # date-time type

dtype('<M8[ns]')

In [71]:
df1 = df

In [72]:
# creating a new column with incorrect date format
df1['DOJ2'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025', '02-04-2025', '25-04-2025', '10-05-2025', '18-05-2025', '30-05-2025', '22-06-2025']
df1

      Name  Age  Salary Team        DOJ        DOJ2
0   Tanmoy   30   30000  CEO 2024-01-01  01-01-2025
1     Usha   18   20000   HR 2024-01-15  15-01-2025
2    Achol   25   15000  CTO 2024-03-28  28-03-2025
3   Samiya   20   10000   DA 2024-03-03  03-03-2025
4    Nizum   22    8000   DS 2024-04-02  02-04-2025
5    Talha   15   12000   ML 2024-04-25  25-04-2025
6  Rodoshi   18   22000   DL 2024-05-10  10-05-2025
7     Rafi   12   45000  SWE 2024-05-18  18-05-2025
8     Ayan   10    5000   IT 2024-05-30  30-05-2025
9    Ahmed    8    7000   SS 2024-06-22  22-06-2025

In [73]:
df1['DOJ2'].dtype  # object-type value

dtype('O')

In [74]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format = '%d-%m-%Y') # change to date-time type using date-format

In [75]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [76]:
df = df.drop('DOJ2', axis=1)
df

      Name  Age  Salary Team        DOJ
0   Tanmoy   30   30000  CEO 2024-01-01
1     Usha   18   20000   HR 2024-01-15
2    Achol   25   15000  CTO 2024-03-28
3   Samiya   20   10000   DA 2024-03-03
4    Nizum   22    8000   DS 2024-04-02
5    Talha   15   12000   ML 2024-04-25
6  Rodoshi   18   22000   DL 2024-05-10
7     Rafi   12   45000  SWE 2024-05-18
8     Ayan   10    5000   IT 2024-05-30
9    Ahmed    8    7000   SS 2024-06-22

In [78]:
# extract year, month, week, day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
4     Tuesday
5    Thursday
6      Friday
7    Saturday
8    Thursday
9    Saturday
Name: DOJ, dtype: object

In [81]:
# create new column using month extract function from DOJ column
df['Month'] = df['DOJ'].dt.month

In [82]:
df

      Name  Age  Salary Team        DOJ  Month
0   Tanmoy   30   30000  CEO 2024-01-01      1
1     Usha   18   20000   HR 2024-01-15      1
2    Achol   25   15000  CTO 2024-03-28      3
3   Samiya   20   10000   DA 2024-03-03      3
4    Nizum   22    8000   DS 2024-04-02      4
5    Talha   15   12000   ML 2024-04-25      4
6  Rodoshi   18   22000   DL 2024-05-10      5
7     Rafi   12   45000  SWE 2024-05-18      5
8     Ayan   10    5000   IT 2024-05-30      5
9    Ahmed    8    7000   SS 2024-06-22      6

In [83]:
df['DOJ'] + pd.Timedelta(days=90) # add 90 days to DOJ column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
4   2024-07-01
5   2024-07-24
6   2024-08-08
7   2024-08-16
8   2024-08-28
9   2024-09-20
Name: DOJ, dtype: datetime64[ns]

#### **8. Handling Missing Values**

In [84]:
df

      Name  Age  Salary Team        DOJ  Month
0   Tanmoy   30   30000  CEO 2024-01-01      1
1     Usha   18   20000   HR 2024-01-15      1
2    Achol   25   15000  CTO 2024-03-28      3
3   Samiya   20   10000   DA 2024-03-03      3
4    Nizum   22    8000   DS 2024-04-02      4
5    Talha   15   12000   ML 2024-04-25      4
6  Rodoshi   18   22000   DL 2024-05-10      5
7     Rafi   12   45000  SWE 2024-05-18      5
8     Ayan   10    5000   IT 2024-05-30      5
9    Ahmed    8    7000   SS 2024-06-22      6

In [85]:
df.isnull() #  Detect missing values

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False
4  False  False   False  False  False  False
5  False  False   False  False  False  False
6  False  False   False  False  False  False
7  False  False   False  False  False  False
8  False  False   False  False  False  False
9  False  False   False  False  False  False

In [87]:
import numpy as np  # to create null values below

In [97]:
df.loc[df.Name=='Achol', 'Salary'] = np.nan # adding a null value

In [98]:
df.loc[df.Name=='Achol', 'DOJ'] = np.nan # adding a null value

In [99]:
df

      Name  Age   Salary Team        DOJ  Month
0   Tanmoy   30  30000.0  CEO 2024-01-01      1
1     Usha   18  20000.0   HR 2024-01-15      1
2    Achol   25      NaN  CTO        NaT      3
3   Samiya   20  10000.0   DA 2024-03-03      3
4    Nizum   22   8000.0   DS 2024-04-02      4
5    Talha   15  12000.0   ML 2024-04-25      4
6  Rodoshi   18  22000.0   DL 2024-05-10      5
7     Rafi   12  45000.0  SWE 2024-05-18      5
8     Ayan   10   5000.0   IT 2024-05-30      5
9    Ahmed    8   7000.0   SS 2024-06-22      6

In [100]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False    True  False   True  False
3  False  False   False  False  False  False
4  False  False   False  False  False  False
5  False  False   False  False  False  False
6  False  False   False  False  False  False
7  False  False   False  False  False  False
8  False  False   False  False  False  False
9  False  False   False  False  False  False

In [101]:
df.isnull().sum() # count of null values by columns

Name      0
Age       0
Salary    1
Team      0
DOJ       1
Month     0
dtype: int64

In [102]:
df.fillna(0) # fill null values with 0

      Name  Age   Salary Team                  DOJ  Month
0   Tanmoy   30  30000.0  CEO  2024-01-01 00:00:00      1
1     Usha   18  20000.0   HR  2024-01-15 00:00:00      1
2    Achol   25      0.0  CTO                    0      3
3   Samiya   20  10000.0   DA  2024-03-03 00:00:00      3
4    Nizum   22   8000.0   DS  2024-04-02 00:00:00      4
5    Talha   15  12000.0   ML  2024-04-25 00:00:00      4
6  Rodoshi   18  22000.0   DL  2024-05-10 00:00:00      5
7     Rafi   12  45000.0  SWE  2024-05-18 00:00:00      5
8     Ayan   10   5000.0   IT  2024-05-30 00:00:00      5
9    Ahmed    8   7000.0   SS  2024-06-22 00:00:00      6

In [103]:
df.loc[df.Name=='Achol', 'Salary'] = 15000

In [105]:
df.loc[df.Name=='Achol', 'DOJ'] = '2024-03-28'

In [106]:
df

      Name  Age   Salary Team        DOJ  Month
0   Tanmoy   30  30000.0  CEO 2024-01-01      1
1     Usha   18  20000.0   HR 2024-01-15      1
2    Achol   25  15000.0  CTO 2024-03-28      3
3   Samiya   20  10000.0   DA 2024-03-03      3
4    Nizum   22   8000.0   DS 2024-04-02      4
5    Talha   15  12000.0   ML 2024-04-25      4
6  Rodoshi   18  22000.0   DL 2024-05-10      5
7     Rafi   12  45000.0  SWE 2024-05-18      5
8     Ayan   10   5000.0   IT 2024-05-30      5
9    Ahmed    8   7000.0   SS 2024-06-22      6

#### **9. Aggregation and Group By**

In [107]:
df['Month'].value_counts() # frequency of values in month column

Month
5    3
1    2
3    2
4    2
6    1
Name: count, dtype: int64

In [108]:
df[df['Month']==1].value_counts() # frequency of values in month column where month=1

Name    Age  Salary   Team  DOJ         Month
Tanmoy  30   30000.0  CEO   2024-01-01  1        1
Usha    18   20000.0  HR    2024-01-15  1        1
Name: count, dtype: int64

In [109]:
# aggregation based on group by
df.groupby('Month')['Salary'].sum() # sum of salary by month

Month
1    50000.0
3    25000.0
4    20000.0
5    72000.0
6     7000.0
Name: Salary, dtype: float64

In [110]:
# different aggregation on different columns
df.groupby('Month').agg({'Salary': 'mean', 'Name': 'count'})

        Salary  Name
Month
1      25000.0     2
3      12500.0     2
4      10000.0     2
5      24000.0     3
6       7000.0     1

#### **10. Concatenate and Merge Dataframe (JOINS)**

In [111]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [112]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

##### What is Concatenate:
Combine objects along a particular axis.

In [113]:
# Concatenate: vertical / row level / top on top
pd.concat([df1, df2], axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [114]:
# Concatenate: horizontal / column level / side on side
pd.concat([df1, df2], axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

##### Merge in Pandas
Performs join operations similar to relational databases like SQL JOINS

In [115]:
# merge = join
pd.merge(df1, df2, how='inner', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [116]:
pd.merge(df1, df2, how='inner', left_on='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

#### **11. AI and ChatGPT**

In [117]:
df

      Name  Age   Salary Team        DOJ  Month
0   Tanmoy   30  30000.0  CEO 2024-01-01      1
1     Usha   18  20000.0   HR 2024-01-15      1
2    Achol   25  15000.0  CTO 2024-03-28      3
3   Samiya   20  10000.0   DA 2024-03-03      3
4    Nizum   22   8000.0   DS 2024-04-02      4
5    Talha   15  12000.0   ML 2024-04-25      4
6  Rodoshi   18  22000.0   DL 2024-05-10      5
7     Rafi   12  45000.0  SWE 2024-05-18      5
8     Ayan   10   5000.0   IT 2024-05-30      5
9    Ahmed    8   7000.0   SS 2024-06-22      6

In [ ]:
# Prompt to filter salary > 70000 and January employees

In [119]:
# Method-1: basic filter
df[(df['Month'] == 1) & (df['Salary'] >= 25000)]

     Name  Age   Salary Team        DOJ  Month
0  Tanmoy   30  30000.0  CEO 2024-01-01      1

In [120]:
# Method-2: query method
df.query("Month == 1 and Salary >= 20000")

     Name  Age   Salary Team        DOJ  Month
0  Tanmoy   30  30000.0  CEO 2024-01-01      1
1    Usha   18  20000.0   HR 2024-01-15      1

##### Home work: Create a dataframe to practice pivot table in pandas (using AI prompt)